version: '2'


services:

  cm-demo-webserver:
    image: phpdockerio/nginx:latest
    container_name: cm-demo-webserver
    volumes_from:
      - cm-demo-folder
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - ${WEBSERVER_PORT}:80
    environment:
      - VIRTUAL_HOST=cm-demo.dev
    network_mode: bridge
    links:
      - cm-demo-php-fpm

  cm-demo-php-fpm:
    build:
      context: ./php-fpm
      args:
        USER_NAME: ${USER}
    container_name: cm-demo-php-fpm
    user: ${USER}
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      DEBUG_CONFIG: remote_host=10.254.254.254
    volumes_from:
      - cm-demo-folder
    volumes:
      - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    network_mode: bridge
    links:
      - cm-demo-mysql
      - cm-demo-redis

  cm-demo-folder:
    image: tianon/true
    container_name: cm-demo-folder
    volumes:
      - "./../:/var/www/cm-demo"

  cm-demo-mysql:
    image: mysql:latest
    container_name: cm-demo-mysql
    volumes_from:
      - cm-demo-folder
    volumes:
      - ./mysql:/etc/mysql/conf.d
    network_mode: bridge
    environment:
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_ROOT_PASSWORD=${DBROOTPASS}

  cm-demo-redis:
    image: redis:latest
    container_name: cm-demo-redis
    network_mode: bridge

volumes:
  cm-demo-folder: